import random
# Generated by Django 2.1 on 2018-08-28 21:29
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    profile_pictures = [
        "asian_student.jpeg",
        "black_and_white_photo.jpg",
        "college_student.jpeg",
        "girl_looking_sideways.jpg",
        "nerdy_guy.jpg",
        "science_student.jpeg",
        "student_sitting_on_grass.jpg",
    ]
    
    for i in range(len(profile_pictures)): 
        profile_pictures[i] = 'potential_pics/' + profile_pictures[i]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=random.choice(profile_pictures), upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
