# Generated by Django 2.2.3 on 2019-09-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet_points',
            field=models.BigIntegerField(default=0),
        ),
    ]
