# Generated by Django 2.2 on 2019-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_wallet_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/college_student.jpeg', upload_to='profile_pics'),
        ),
    ]
