# Generated by Django 2.1 on 2019-12-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191103_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/black_and_white_photo.jpg', upload_to='profile_pics'),
        ),
    ]
