# Generated by Django 2.1 on 2019-12-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191224_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/student_sitting_on_grass.jpg', upload_to='profile_pics'),
        ),
    ]
