# Generated by Django 2.1 on 2019-12-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191224_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/girl_looking_sideways.jpg', upload_to='profile_pics'),
        ),
    ]
