# Generated by Django 2.1 on 2020-01-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191225_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/science_student.jpeg', upload_to='profile_pics'),
        ),
    ]
