# Generated by Django 2.1 on 2020-01-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200117_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/girl_looking_sideways.jpg', upload_to='profile_pics'),
        ),
    ]
