# Generated by Django 2.1 on 2020-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200320_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='post',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/asian_student.jpeg', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
