# Generated by Django 2.1 on 2020-03-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200320_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/college_student.jpeg', upload_to='profile_pics'),
        ),
    ]
