# Generated by Django 2.1 on 2020-03-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200320_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/black_and_white_photo.jpg', upload_to='profile_pics'),
        ),
    ]
