# Generated by Django 2.1 on 2020-03-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200320_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/student_sitting_on_grass.jpg', upload_to='profile_pics'),
        ),
    ]
