# Generated by Django 2.1.5 on 2020-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20200320_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/asian_student.jpeg', upload_to='profile_pics'),
        ),
    ]
