# Generated by Django 2.1.5 on 2020-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200320_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/science_student.jpeg', upload_to='profile_pics'),
        ),
    ]
