# Generated by Django 2.1.5 on 2020-03-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20200320_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/girl_looking_sideways.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Economics', 'Economics'), ('Chemical Engineering', 'Chemical Engineering'), ('History', 'History'), ('Psychology', 'Psychology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(choices=[('UM', 'University of Manchester'), ('ICL', 'Imperial College London'), ('UCL', 'University College London'), ('UL', 'University of Leeds'), ('UO', 'University of Oxford')], max_length=100),
        ),
    ]
