# Generated by Django 2.1.5 on 2020-05-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20200508_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/asian_student.jpeg', upload_to='profile_pics/'),
        ),
    ]
