# Generated by Django 2.1.5 on 2020-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20200508_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/girl_looking_sideways.jpg', upload_to='profile_pics/'),
        ),
    ]
