# Generated by Django 2.1.5 on 2020-05-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20200508_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='potential_pics/nerdy_guy.jpg', upload_to='profile_pics/'),
        ),
    ]
