# Generated by Django 2.2.3 on 2019-08-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='start_time',
        ),
        migrations.AddField(
            model_name='post',
            name='time_studied',
            field=models.IntegerField(default=0),
        ),
    ]
