# Generated by Django 2.2.3 on 2019-09-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190813_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackendTimer',
        ),
        migrations.AlterField(
            model_name='post',
            name='time_studied',
            field=models.IntegerField(default=20),
        ),
    ]
