# Generated by Django 2.1 on 2020-01-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190911_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_description',
            field=models.CharField(default='user description', max_length=40),
            preserve_default=False,
        ),
    ]
