# Generated by Django 2.1 on 2020-01-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_description',
            field=models.CharField(default='Session at 21:51:55', max_length=40),
        ),
    ]
