# Generated by Django 2.1 on 2020-03-16 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
