# Generated by Django 2.1 on 2020-03-20 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_competitionparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionparticipant',
            name='datetime_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
