# Generated by Django 2.1 on 2020-03-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionparticipant',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Event'),
        ),
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Event'),
        ),
    ]
