# Generated by Django 2.1 on 2020-03-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200320_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionparticipant',
            name='event',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Event'),
        ),
    ]
