# Generated by Django 2.1 on 2020-03-20 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200320_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='blog.Event'),
        ),
    ]
