# Generated by Django 2.1 on 2020-03-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200320_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionparticipant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.CompetitionParticipant'),
        ),
        migrations.AddField(
            model_name='event',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
