# Generated by Django 2.1.5 on 2020-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200320_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='points_requires',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
