# Generated by Django 2.1.5 on 2020-03-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_competition_points_requires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='points_requires',
            new_name='points_required',
        ),
    ]
