# Generated by Django 2.1.5 on 2020-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200320_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='reward_description',
            field=models.CharField(default='description', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='reward_image',
            field=models.ImageField(default='default.jpg', upload_to='rewards'),
        ),
        migrations.AddField(
            model_name='competition',
            name='reward_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
