# Generated by Django 2.2 on 2019-06-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
