# Generated by Django 2.2 on 2019-06-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
